[project]
name = "bleachbit"
version = "2025.2.9.4"
description = "Clean Your System and Free Disk Space."
readme = "README_soda.md"
requires-python = ">=3.10"
dependencies = ["msys2_env", "winshell"]


[project.urls]
Repository = "https://github.com/soda92/bleachbit"

[project.scripts]
bleachbit = "bleachbit_loader.main:main"

[build-system]
requires = ["hatchling", "hatch-build-scripts"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
ignore-vcs = true
packages = [
    "bleachbit_loader",
    "bleachbit_loader.bleachbit",
    "bleachbit_loader.bleachbit.markovify",
    "bleachbit_loader.data",
    "bleachbit_loader.cleaners",
    "bleachbit_loader.windows",
]
include = ["*.ico", "*.ps1", "*.ui", "*.xml"]
exclude = ["*.kra", "__pycache__"]

[tool.hatch.build.targets.wheel]
ignore-vcs = true
packages = [
    "bleachbit_loader",
    "bleachbit_loader.bleachbit",
    "bleachbit_loader.bleachbit.markovify",
    "bleachbit_loader.data",
    "bleachbit_loader.windows",
    "bleachbit_loader.cleaners",
]
include = ["*.ico", "*.ps1", "*.ui", "*.xml"]
exclude = ["*.kra", "__pycache__"]

[[tool.hatch.build.hooks.build-scripts.scripts]]
work_dir = "."
out_dir = "bleachbit_loader/__pycache__"
commands = [
    "powershell bleachbit_loader/build.ps1",
]
artifacts = [
    "bleachbit_loader/tmp.txt",
]
